spring.application.name=Data Segmentation
spring.mvc.view.prefix=/views/
#spring.mvc.view.suffix=.jsp

server.port=9098
#spring.security.user.name=admin
#spring.security.user.password=admin123
#spring.security.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/empl
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security=DEBUG

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.username=coachingswt@gmail.com
mail.smtp.password=yzuh lefx xkkt ussk
